

```{r libraries, echo=FALSE}
library(ggplot2)
library(dplyr)
```

```{r paths, echo=FALSE}
PROJECT_ROOT <- getwd()
#OUTPUT_DIR <- file.path(PROJECT_ROOT, "datasets", "pseudobulk")
#dir.create(OUTPUT_DIR, recursive = TRUE, showWarnings = FALSE)
```

## Displaying the distribution of cells per donor as histogram
```{r count, echo=FALSE}

counts <- read.csv(file.path(PROJECT_ROOT, "datasets", "pseudobulk", "CD14-positive monocyte.csv"))
rownames(counts) <- counts[,1]
counts <- counts[,-1]
counts

colData <- read.csv(file.path(PROJECT_ROOT, "datasets", "pseudobulk", "coldata_CD14-positive monocyte.csv"))
colData <- colData %>% filter(smoking_status == 0)

ggplot(colData, aes(x = n_cells)) +
  geom_histogram(bins = 75, fill = "steelblue", color = "white") +
  labs(
    x = "Number of Cells",
    y = "Frequency"
  ) +
  theme_minimal(base_size = 14)
```


```{r pseudobulk analsis, echo=FALSE, fig.width=6, fig.height=6}

colData <- colData %>% filter( smoking_status == 0)
colData$sex <- factor(colData$sex, levels = c("male","female"), labels = c("Male","Female"))

metadata_binned <- colData %>%
  count(sex)

gg_bar_sex <- ggplot(metadata_binned, aes(x = sex, y = n, fill = sex)) +
  geom_col(width = 0.6, alpha = 0.9) +
  geom_text(aes(label = n), vjust = -0.4, size = 8) +
  labs(
    x = "",
    y = "Number of individuals",
    fill = "Sex"
  ) +
  scale_fill_manual(
    values = c("Male" = "#4DBBD5", "Female" = "#E64B35")
  ) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x  = element_text(size = 24),
    axis.text.y  = element_text(size = 24),
    legend.position = "none",
    axis.title = element_text(face = "bold")
  )

gg_bar_sex
ggsave("./MA_Thesis/figures/AIDA/gg_bar_sex.png", plot = gg_bar_sex, width = 6, height = 8, dpi = 300)


#colData$sex <- ifelse(colData$sex == 1, "female", "male")
ggplot(colData, aes(x = sex, y = age, fill = sex)) +
  geom_violin(alpha = 0.6) +
  geom_boxplot(width=0.1, fill="white") +  # optionale Box im Violin
  scale_fill_manual(values = c("Male"="#4DBBD5", "Female"="#E64B35")) +
  labs(title="Altersverteilung nach Geschlecht", x="Geschlecht", y="Alter") +
  theme_minimal()

n_cells <- ggplot(colData, aes(x = sex, y = n_cells, fill = sex)) +
  geom_violin(alpha = 0.7, width = 0.8, color = NA) +
  geom_boxplot(width = 0.15, fill = "white", outlier.shape = NA) +
  scale_fill_manual(values = c("Male" = "#4DBBD5", "Female" = "#E64B35")) +
  labs(
    x = "",
    y = "Number of CD14+ monocyte cells"
  ) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x  = element_text(size = 24),
    axis.text.y  = element_text(size = 24),
    legend.position = "none",
    axis.title = element_text(face = "bold")
  )

n_cells
ggsave("./MA_Thesis/figures/AIDA/n_cells.png",n_cells, width = 6, height = 8, dpi = 300)

ggsave("./MA_Thesis/figures/AIDA/gg_bar_sex.png", plot = gg_bar_sex, width = 6, height = 8, dpi = 300)legend.position = "top")
```